server:
  port: 8187

spring:
  application:
    name: md-main
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

tpd:
  topic-name: advice-topic
  messages-per-request: 10
  
rest-parameter:
  topic:
    retrieve.info.data:
      - steps
      - next
      - symbol
    retrieve.historical.data:
      - steps
      - next
      - symbol
      - date
    parse.historical.data:
      - steps
      - next
      - symbol
    parse.exchange.data:
      - steps
      - next
      - subExchange
    parse.info.data:
      - steps
      - next
      - symbol
    parse.detail.data.list:
      - steps
      - next
      - subExchange
    dbget.exchange.data:
      - steps
      - next
      - subExchange