spring:
  application:
    name: md-storage
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: marketdata
      port: 27017
      host: localhost
      
tpd:
  topic-name: advice-topic
  messages-per-request: 10    
  
server:
  port: 8186
   
md-storage:
  controller:
    enabled: true