server:
  port: 8184

spring:
  application:
    name: md-storage
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: marketdata
      port: 27017
      host: localhost 
   
md-storage:
  controller:
    enabled: true