spring:
  application:
    name: md-storage
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: marketdata
      port: 27017
      host: localhost
      
tpd:
  topic-name: advice-topic
  messages-per-request: 10    
  
server:
  port: 8184
   
md-storage:
  controller:
    enabled: true
    
    
map-key-parameter:
  wait: wait
  steps: steps
  next: next
  total: total
  type: type
  exchange: exchange
  subExchange: subExchange  
  name: name
  ticker: ticker
  symbol: symbol
  date: date
  time: time
  open: open
  high: high
  low: low    
  close: close
  adjClose: adjClose
  prevClose: prevClose
  volume: volume
  percentChange: percentChange  
  year: year
  month: month
  day: day
  weekOfYear: weekOfYear
  yearForWeek: yearForWeek
  dayOfYear: dayOfYear
  dayOfWeek: dayOfWeek  
  fromDate: fromDate
  fromYear: fromYear
  fromMonth: fromMonth
  fromDay: fromDay
  fromWeekOfYear: fromWeekOfYear
  fromDayOfWeek: fromDayOfWeek
  fromYearForWeek: fromYearForWeek
  toDate: toDate
  toYear: toYear
  toMonth: toMonth
  toDay: toDay
  toWeekOfYear: toWeekOfYear
  toDayOfWeek: toDayOfWeek
  toYearForWeek: toYearForWeek 
  suffixValue: value
  suffixSize: size
  suffixHigh: high
  suffixLow: low
  historicalHigh: historicalHigh
  historicalLow: historicalLow
  historicalHighDate: historicalHighDate
  historicalLowDate: historicalLowDate
  newHigh: newHigh
  newLow: newLow
  exchangeName: exchangeName
  country: country
  currency: currency
  industry: industry
  sector: sector
  beta: beta
  forwardPE: forwardPE
  priceToBook: priceToBook
  sharesOutstanding: sharesOutstanding
  marketCap: marketCap
  dataType: dataType
  dataSource: dataSource  
  from: from