spring:
  cloud:
    config:
      enabled: false
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      
tpd:
  topic-name: advice-topic
  messages-per-request: 10    

map-key-parameter:
  wait: wait
  steps: steps
  next: next
  total: total
  type: type
  interval: interval
  exchange: exchange
  subExchange: subExchange
  name: name
  market: market
  ticker: ticker
  symbol: symbol
  date: date
  time: time
  open: open
  high: high
  low: low    
  close: close
  adjClose: adjClose
  prevClose: prevClose
  volume: volume
  percentChange: percentChange
  year: year
  month: month
  day: day
  weekOfYear: weekOfYear
  yearForWeek: yearForWeek
  dayOfYear: dayOfYear
  dayOfWeek: dayOfWeek  
  fromDate: fromDate
  fromYear: fromYear
  fromMonth: fromMonth
  fromDay: fromDay
  fromWeekOfYear: fromWeekOfYear
  fromDayOfWeek: fromDayOfWeek
  fromYearForWeek: fromYearForWeek
  toDate: toDate
  toYear: toYear
  toMonth: toMonth
  toDay: toDay
  toWeekOfYear: toWeekOfYear
  toDayOfWeek: toDayOfWeek
  toYearForWeek: toYearForWeek 
  suffixHigh: high
  suffixLow: low
  historicalHigh: historicalHigh
  historicalLow: historicalLow
  historicalHighDate: historicalHighDate
  historicalLowDate: historicalLowDate
  newHigh: newHigh
  newLow: newLow
  exchangeName: exchangeName
  country: country
  currency: currency
  industry: industry
  sector: sector
  beta: beta
  forwardPE: forwardPE
  priceToBook: priceToBook
  sharesOutstanding: sharesOutstanding
  marketCap: marketCap
  dataType: dataType
  dataSource: dataSource
  directory: directory
  fileName: fileName
  from: from
  historicalTotal: historicalTotal
  historicalFirstDate: historicalFirstDate
  historicalLastDate: historicalLastDate
  lastPrice: lastPrice
  ind: ind
  limit: limit
  
map-value-parameter:
  daily: D
  weekly: W
  monthly: M
  
indicator:
  sma:
    - 21
    - 50
    - 150
    - 200

json-node:
  property:
    forwardPE:
      - defaultKeyStatistics
      - forwardPE
      - raw
    sharesOutstanding:
      - defaultKeyStatistics
      - sharesOutstanding
      - raw
    beta:
      - defaultKeyStatistics
      - beta
      - raw
    priceToBook:
      - defaultKeyStatistics
      - priceToBook
      - raw
    industry:
      - summaryProfile
      - industry
    sector:
      - summaryProfile
      - sector
    country:
      - summaryProfile
      - country
    exchange:
      - price
      - exchange
    exchangeName:
      - price 
      - exchangeName
    type:
      - price
      - quoteType
    ticker:
      - price
      - symbol
    name:
      - price
      - longName
    currency:
      - price
      - currency
    marketCap:
      - price
      - marketCap
      - raw