server:
  port: 8185

spring:
  application:
    name: md-enricher
  cloud:
    config:
      enabled: false    
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

tpd:
  topic-name: advice-topic
  messages-per-request: 10    

map-key-parameter:
  total: total
  type: type
  exchange: exchange
  name: name
  symbol: symbol
  date: date
  open: open
  high: high
  low: low    
  close: close
  adjClose: adjClose
  volume: volume
  year: year
  month: month
  day: day
  weekOfYear: weekOfYear
  yearForWeek: yearForWeek
  dayOfYear: dayOfYear
  dayOfWeek: dayOfWeek  
  fromDate: fromDate
  fromYear: fromYear
  fromMonth: fromMonth
  fromDay: fromDay
  fromWeekOfYear: fromWeekOfYear
  fromDayOfWeek: fromDayOfWeek
  fromYearForWeek: fromYearForWeek
  toDate: toDate
  toYear: toYear
  toMonth: toMonth
  toDay: toDay
  toWeekOfYear: toWeekOfYear
  toDayOfWeek: toDayOfWeek
  toYearForWeek: toYearForWeek 
  suffixMA: ma
  suffixSum: sum
  suffixFirst: first
  suffixSize: size
  suffixHigh: high
  suffixLow: low
  historicalHigh: historicalHigh
  historicalLow: historicalLow
  historicalHighDate: historicalHighDate
  historicalLowDate: historicalLowDate
  newHigh52W: newHigh52W
  newLow52W: newLow52W
  
map-value-parameter:
  daily: daily
  weekly: weekly
  monthly: monthly
  
indicator:
  sma:
    - 21
    - 50
    - 150
    - 200