spring:
  cloud:
    config:
      enabled: false
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      
tpd:
  topic-name: advice-topic
  messages-per-request: 10    

kafka:
  topic:
    create-dailysummary-list: create-dailysummary-list
    enrich-exchange-list: enrich-exchange-list
    enrich-historical-list: enrich-historical-list
    enrich-analysis-list: enrich-analysis-list
    parse-daily-list: parse-daily-list
    parse-daily-single: parse-daily-single
    parse-historical-list: parse-historical-list
    parse-detail-list: parse-detail-list
    parse-detail-single: parse-detail-single
    parse-info-single: parse-info-single
    parse-exchange-data: parse-exchange-data
    parse-historical-single: parse-historical-single
    save-dailysummary-list: save-dailysummary-list
    save-tradedate-list: save-tradedate-list
    save-exchange-list: save-exchange-list
    save-analysis-list: save-analysis-list
    save-historical-list: save-historical-list
    save-instrument-list: save-instrument-list
    save-instrument-single: save-instrument-single
    dbget-exchange-data: dbget-exchange-data
    dbget-total-from-instrument: dbget-total-from-instrument
    dbget-summary-single: dbget-summary-single
    dbget-summary-list: dbget-summary-list
    dbget-historical-single: dbget-historical-single
    dbget-historical-list: dbget-historical-list
    dbget-analysis-single: dbget-analysis-single
    dbget-analysis-list: dbget-analysis-list
    dbget-tradedate-single: dbget-tradedate-single
    dbget-tradedate-list: dbget-tradedate-list
    dbget-analysis-tradedate: dbget-analysis-tradedate
    dbget-dailysummary-single: dbget-dailysummary-single
    dbupdate-historical-all: dbupdate-historical-all
    retrieve-yahoo-single: retrieve-yahoo-single 
    retrieve-yahoo-list: retrieve-yahoo-list
    consolidate-historical-ticker: consolidate-historical-ticker
    
map-key-parameter:
  wait: wait
  steps: steps
  next: next
  total: total
  type: type
  interval: interval
  exchange: exchange
  subExch: subExch
  name: name
  market: market
  ticker: ticker
  symbol: symbol
  date: date
  time: time
  open: open
  high: high
  low: low    
  close: close
  adjClose: adjClose
  prevClose: prevClose
  volume: volume
  percentChange: percentChange
  year: year
  month: month
  day: day
  weekOfYear: weekOfYear
  yearForWeek: yearForWeek
  dayOfYear: dayOfYear
  dayOfWeek: dayOfWeek  
  fromDate: fromDate
  fromYear: fromYear
  fromMonth: fromMonth
  fromDay: fromDay
  fromWeekOfYear: fromWeekOfYear
  fromDayOfWeek: fromDayOfWeek
  fromYearForWeek: fromYearForWeek
  toDate: toDate
  toYear: toYear
  toMonth: toMonth
  toDay: toDay
  toWeekOfYear: toWeekOfYear
  toDayOfWeek: toDayOfWeek
  toYearForWeek: toYearForWeek 
  suffixHigh: high
  suffixLow: low
  hHigh: hHigh
  hLow: hLow
  hHighD: hHighD
  hLowD: hLowD
  newHigh: newHigh
  newLow: newLow
  exchangeN: exchangeN
  country: country
  currency: currency
  industry: industry
  sector: sector
  beta: beta
  FPE: FPE
  PB: PB
  sharesO: sharesO
  mCap: mCap
  dataType: dataType
  dataSource: dataSource
  directory: directory
  fileName: fileName
  from: from
  hTotal: hTotal
  hFirstD: hFirstD
  hLastD: hLastD
  lastP: lastP
  ind: ind
  inst: inst
  limit: limit
  save: save
  group: group
  yahooIndustry: y
  format: format
  length: length
  method: method
  dataFormat: dataFormat
  requestID: requestID
  
map-value-parameter:
  daily: D
  weekly: W
  monthly: M
  
indicator:
  sma:
    - 21
    - 50
    - 150
    - 200

json-node:
  property:
    FPE:
      - defaultKeyStatistics
      - forwardPE
      - raw
    sharesO:
      - defaultKeyStatistics
      - sharesOutstanding
      - raw
    beta:
      - defaultKeyStatistics
      - beta
      - raw
    PB:
      - defaultKeyStatistics
      - priceToBook
      - raw
    industry:
      - summaryProfile
      - industry
    sector:
      - summaryProfile
      - sector
    country:
      - summaryProfile
      - country
    exchange:
      - price
      - exchange
    exchangeN:
      - price 
      - exchangeName
    type:
      - price
      - quoteType
    ticker:
      - price
      - symbol
    name:
      - price
      - longName
    currency:
      - price
      - currency
    mCap:
      - price
      - marketCap
      - raw