eureka:
  client:
    service-url:
      defaultZone: http://md-registry:8081/eureka
  instance:
    hostname: md-api-gateway

## SECURITY BASED CONFIGURATIONS
app:
  config:
    keycloak:
      url: http://keycloak:8080/auth
      realm: SpringBootKeycloak
      client-secret: d0cce31e-99a3-4b45-bfb4-2283cc32e8b3
      client-id: internet-banking-core-client

spring:
  ## API SECURITY WITH KEYCLOAK PROVIDER
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            user-info-authentication-method: header
            user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          internet-banking-core-client:
            authorization-grant-type: authorization_code
            client-id: ${app.config.keycloak.client-id}
            client-secret: ${app.config.keycloak.client-secret}
            provider: keycloak
            redirect-uri: http://keycloak:8080/login/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs