server:
  port: 8184

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: marketdata
      port: 27017
      host: localhost 